declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Název webové části (režim pouze pro obsah)",
    LPViewerPropertyDescription: "Vlastní vlastnosti učení",
    LPViewerPropertyGroupName: "Výchozí zobrazení",
    WebpartModeLabel: "Vybrat režim webových částí",
    WebpartModeDescription: "Jak chcete zobrazit webovou část",
    ShowNavigationLabel: "Zobrazit vlastní navigační záhlaví výuky",
    DefaultFilterLabel: "Výběr filtru",
    DefaultFilterDescription: "Chcete-li omezit výsledky, vyberte filtr. Filtrovat lze současně pouze podle jednoho typu.",
    DefaultCategoryLabel: "Filtrovat do kategorie",
    DefaultCategoryDescription: "Výběrem kategorie omezíte výsledky.",
    DefaultSubCategoryLabel: "Filtrovat do podkatem",
    DefaultSubCategoryDescription: "Výběrem podkatedru pro omezení výsledků.",
    DefaultPlaylistLabel: "Filtrování do seznamu stop",
    DefaultPlaylistDescription: "Výběrem kategorie omezíte výsledky.",
    DefaultAssetLabel: "Výběr majetku",
    DefaultAssetDescription: "Vyberte datový zdroj, který se má zobrazit v seznamu stop.",
    FilterPanelHeader: "Vyberte si kurzy, které vám nejlépe vyhovují",
    FilterPanelAudienceLabel: "Jsem",
    FilterPanelSkillsetLabel: "Moje dovednosti jsou",
    NavigationHome: "Domov",
    SearchResultItemPlayListLabel: "Seznam stop: ",
    SearchResultItemCategoryLabel: "Kategorie: ",
    SearchPanelPlaceHolderLabel: "Hledání seznamů stop nebo datových zdrojů",
    LinkPanelCopyLabel: "Kopírovat",
    HeaderPlaylistPanelCurrentPlaylistLabel: "Aktuální seznam stop: ",
    HeaderPlaylistPanelAdminHeader: "Administrativa",
    PlaylistOverviewDesignMessage: "Během používání tato oblast zobrazí další datové zdroje v seznamu skladeb, ve které se zobrazuje.",
    PlaylistOverviewHeading: "Všechny kroky v seznamu stop",
    BurgerButton: "Hamburger",
    LinkButton: "Propojit",
    SearchButton: "Hledání",
    AdministerPlaylist: "Správa seznamu stop",
    NoSearchResults: "Dotazu se neshoduje žádné výsledky hledání.",
    DefaultCDNLabel: "Vybrat zdroj učení",
    DefaultCDNDescription: "Vyberte alternativní zdroj pro výuku obsahu.",
    DescriptionFieldLabel: "Pole popisu",
    ImageSelectorLabel: "Výběr obrázku",
    ImageSelectorButton: "Zvolit obrázek",
    DetailEditTitle: "Titul",
    DetailEditDescription: "Popis",
    DetailEditUrl: "Adresa URL",
    DetailEditCategory: "Kategorie",
    DetailEditCategoryNoData: "Nejsou k dispozici žádné kategorie.",
    DetailEditTechnology: "Technologie",
    DetailEditLevel: "Úroveň",
    DetailEditAudience: "Obecenstvo",
    AssetSearchPlaceHolderLabel: "Hledání existujících datových zdrojů",
    CategoryHeading: "Přidat novou podkategorii",
    CategoryHeadingLabel: "Podkategorie",
    CategoryPlaylistSavedMessage: "Seznam skladeb byl uložen!",
    CategoryPlaylistSaveFailedMessage: "Uložení seznamu stop se nezdařilo!",
    CategoryNewPlayListMessage: "Provedli jste změny v novém seznamu stop. Chcete změny zahodit a pokračovat?",
    CategoryEditedPlayListMessage: "V tomto seznamu stop jste provedli změny. Chcete změny zahodit a pokračovat?",
    PlaylistEditAssetSavedMessage: "Aktivum bylo zachráněno!",
    PlaylistEditAssetSaveFailedMessage: "Uložení majetku se nezdařilo!",
    PlaylistEditCreatePlaylistHeader: "Vytvoření nového seznamu stop",
    PlaylistEditPlaylistDetailsHeader: "Podrobnosti o seznamu stop: ",
    PlaylistEditPlaylistAssetsHeader: "Datové zdroje seznamu stop",
    PlaylistEditEditLabel: "Upravit podrobnosti",
    PlaylistEditSaveLabel: "Uložit podrobnosti",
    PlaylistEditCancelLabel: "Zrušit podrobnosti",
    PlaylistEditCloseLabel: "Zavřít seznam stop",
    AssetDetailsCreateHeader: "Vytvoření nového majetku",
    AssetDetailsManageHeader: "Správa vlastního majetku:",
    AssetDetailsDetailsHeader: "Podrobnosti o majetku: ",
    AssetDetailsSaveLabel: "Uložit datový zdroj",
    AssetDetailsCancelLabel: "Zrušit majetek",
    AssetDetailsCloseLabel: "Zavřít majetek",
    AssetDetailsOpenPage: "Otevřít stránku",
    TechnologyHeadingLabel: "Technologie",
    SubcategoryHeadingLabel: "Nadpis podkategorie",
    PlaylistItemPlaylistHeadingLabel: "Seznam stop",
    PlaylistItemPlaylistDelete: "Odstranit seznam stop",
    PlaylistEditAssetNewLabel: "Nový majetek",
    PlaylistRemove: "Odebrat ze seznamu stop",
    ImageSelectorImageAlt: "Vlastní seznam stop",
    ImageSelectorUrlPlaceholder: "Adresa URL obrázku",
    CategoryHeadingAddPlaylistToSubcategory: "Přidání nového seznamu stop do podkategorie",
    AdminMenuTechnologyLabel: "Technologie",
    AdminMenuCategoryLabel: "Kategorie",
    Show: "Ukázat",
    Hide: "Schovat",
    Add: "Přidat",
    Edit: "Upravit",
    CloseButton: "Zavřít",
    EditButton: "Upravit",
    StepButton: "Krok",
    MoveUpButton: "Povýšit",
    MoveDownButton: "Přesunout dolů",
    SaveButton: "Uložit",
    CancelButton: "Zrušit",
    UpdateButton: "Aktualizace",
    DeleteButton: "Vymazat",
    DetailEditNewPageMessage: "Nová stránka datových zdrojů v knihovně stránek webu.",
    DetailEditExistingPageMessage: "Zadejte adresu URL existující stránky.",
    DetailEditNewPageButton: "Stránka Vytvořit datový zdroj",
    DetailEditExistingPageButton: "Zadat adresu URL",
    AdminAddCdnLabel: "Přidat balíček obsahu",
    AdminEditCdnLabel: "Upravit balíček obsahu",
    AdminDeleteCdnLabel: "Odstranit balíček obsahu",
    AdminCdnIdLabel: "ID balíčku obsahu/ID partnera",
    AdminCdnDisplayName: "Zobrazovaný název",
    AdminCdnBaseUrl: "Základní adresa URL",
    AdminCustomCdnTitle: "Vlastní balíček obsahu",
    AdminCustomCdnDescription: "Vlastní balíčky obsahu jsou pokročilou funkcí a měli by je používat pouze správci se zkušenostmi se řešivými webovým obsahem. Nedůvěryhodné zdroje obsahu mohou na váš web vystavit nebezpečný obsah. Měli byste přidávat pouze zdroje, které důvěřujete. Další informace najdete v tématu Pokyny pro partnera v dokumentaci k výukových cestách.",
    AdminConfirmContentPack: "Byla spuštěna nová karta prohlížeče, která vám umožní zřídit novou sadu obsahu. Po úspěšném dokončení aktualizujte seznam alternativního obsahu klepnutím na tlačítko Dokončit níže. Pokud dojde k chybě nebo se rozhodnete balíček obsahu neinstalovat, klikněte na tlačítko Storno, můžete se kdykoli vrátit.",
    AdminCdnCompleteButton: "Kompletní",
    AdminCdnCancelButton: "Zrušit",
    AdminCdnSaveButton: "Uložit",
    AdminCdnUpdateButton: "Aktualizace",
    AdminRemoveCdn: "Potvrďte, že chcete odebrat vybranou CDN?",
    AdminAbout: "Webová část",
    DocumentationLinkLabel: "Otevřete dokumentaci k výukové cestě M365",
    CategoryCopyPlaylistFail: "Kopírování seznamu stop se nezdařilo, obraťte se na správce nebo se podívejte na konzolu prohlížeče, kde najdete další podrobnosti.",
    PlaylistEditCopyLabel: "Kopírovat seznam stop",
    PlaylistNext: "Další",
    PlaylistPrevious: "Předchozí",
    PlaylistFullScreen: "Přepnutí režimu celé obrazovky",
    FilterNotSet: "Všichni",
    AdminVersionUpdateNotice: "Nainstalovaná webová část s výukovými cestami Microsoftu 365 je za neautuální. Aktuálně spuštěna verze %0% a nejnovější verze je %1%.",
    AdminVersionUpdateInstructions: "Podívejte se na pokyny pro 'Aktualizaci řešení'.",
    AdminSecurityMessage: "K administraci výukových cest Microsoftu 365 nemajíte práva. O připojení ke skupině Vlastníci nebo členové se obraťte na správce.",
    AdminConfigIssueMessage: "Výukové cesty Microsoftu 365 mají problém s konfigurací. Požádejte správce o pomoc. [Administrators: Podrobné protokoly naleznete v konzole prohlížeče. Technickou pomoc najdete v seznamu problémů na https://github.com/pnp/custom-learning-office-365/issues.]",
    AdminAwaitingUrlPrompt: "Url: Čekání na titul...",
    CreatingPage: "Vytváření stránky",
    TryAgain: "Zkuste to znovu",
    AddLanguagePlaceholder: "Přidání jazyka",
    NotApplicable: "1999",
    DataUpgradeTitle: "Upgrade dat z",
    DataUpgradeIntro: "Aktualizovali jste hlavní novou verzi výukových cest Microsoftu 365. Chcete-li zahájit proces upgradu, stiskněte tlačítko Start.",
    DataUpgradeStart: "Začínat",
    DataUpgradeClose: "Zavřít",
    DataUpgradeIssue: "Pokud narazíte na problémy s prováděním aktualizace, můžete požádat o pomoc odesláním problému ",
    DataUpgradeIssueLink: "Seznam problémových cest GitHubu pro Výukové cesty Microsoftu 365",
    DataUpgradeLog: "Protokol upgradu",
    DataUpgradeComplete: "Upgrade byl dokončen.",
    DataUpgradeErrors: "Chyby",
    LogLevel: "Úroveň",
    LogMessage: "Zpráva",
    AboutGroupHeader: "M365 výukové cesty",
    AboutGroupTitle: "Aktuální konfigurace*",
    AboutGroupTitle2: "(* bude aktuální obsah specifický)",
    AboutLearningSiteUrl: "Adresa URL studijního webu:",
    AboutBaseCDNPath: "Základní cesta CDN:",
    AboutTelemetryStatus: "Stav telemetrie:",
    AboutCurrentWPVersion: "Aktuální verze webové části:",
    AboutMultilingualEnabled: "Vícejazyčné stránky povoleny:",
    AboutMultilingualLanguages: "Jazyky překladu vícejazyčných stránek:",
    AboutConfiguredLanguages: "Nakonfigurované jazyky:",
    AboutSupportedLanguages: "Jazyky podporované balíčkem obsahu:",
    AboutDefaultSiteLanguage: "Výchozí jazyk webu:",
    AboutCurrentUserLanguage: "Aktuální uživatelský jazyk:",
    AboutContentPackAssetOrigins: "Původ majetku balíčku obsahu:",
    AboutCurrentCDN: "Aktuální CDN:",
    AboutAllCDNs: "Všechny názvy CDN:",
    AboutCacheLastUpdate: "Poslední aktualizace mezipaměti:",
    DocumentLibraries: "Knihovny dokumentů",
    OpenButtonLabel: "Otevřený",
    CancelButtonLabel: "Zrušit",
    UploadFileHeader: "Odeslat soubor",
    ChangeFileLinkLabel: "Změna souboru",
    ChooseFileLinkLabel: "Zvolit soubor",
    AddFileButtonLabel: "Přidat soubor",
    WebSearchLinkLabel: "Vyhledávání na webu",
    CreativeCommonsMessage: "Tyto výsledky jsou označeny licencemi Creative Commons. Zkontrolujte licence, abyste se ujistili, že dodržujete předpisy.",
    CopyrightWarning: "Jste zodpovědní za dodržování práv druhých, včetně autorských práv.",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    LearnMoreLink: "Víc se uč.",
    NoResultsBadEnglish: "Nebyl nalezen žádný výsledek. Pokuste se změnit možnosti filtru",
    SearchResultAlt: "Výsledek obrázku pro {0}.",
    SearchResultAriaLabel: "Stisknutím klávesy ENTER otevřete zdroj obrázku na nové kartě.",
    SearchBoxPlaceholder: "Vyhledávání na webu",
    PoweredByBing: "Poháněno Bingem",
    SizeOptionAll: "Všichni",
    SizeOptionExtraLarge: "Extra velký",
    SizeOptionLarge: "Velký",
    SizeOptionMedium: "Středně",
    SizeOptionSmall: "Malý",
    LayoutOptionAll: "Všichni",
    LayoutOptionSquare: "Náměstí",
    LayoutOptionTall: "Vysoký",
    LayoutOptionWide: "Široký",
    LicenseOptionAll: "Všichni",
    LicenseOptionAny: "Pouze Creative Commons",
    RecentDocumentsHeader: "Poslední dokumenty",
    Loading: "Nakládka...",
    NoRecentFiles: "Žádné poslední soubory",
    NoRecentFilesDescription: "Zkuste vybrat soubor z webu nebo ho nahrajte ze zařízení.",
    EditedByNamePlate: "upraveno ",
    LinkHeader: "Z odkazu",
    LinkFileInstructions: "Vložení odkazu na soubor na OneDrivu pro firmy nebo SharePointu Online",
    NoExternalLinksValidationMessage: "Podporujeme pouze propojení se soubory ve vaší vlastní organizaci.",
    ProvidedValueIsInvalid: "Zadaná hodnota je neplatná.",
    ImageAriaLabelTemplate: ". {0} obrázek",
    DocumentLabelTemplate: "{0}, Dokument, {1}, upraveno {2}, Soukromé",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}, Složka, {1}, upraveno {2}, {3} položky, Soukromé",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 bajtů",
    SizeUnit: [
      "bytes",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "Výběr souborů",
    OrgAssetsTabLabel: "Obrázky a soubory poskytované vaší organizací",
    RecentLinkLabel: "Nedávný",
    SiteLinkLabel: "Poloha",
    UploadLinkLabel: "Upload",
    FromLinkLinkLabel: "Z odkazu",
    TypeAriaLabel: "Operace sloupce pro Typ souboru, Stisknutím seřadíte podle typu Soubor",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "Složka",
    ImageAltText: ". {0} obrázek",
    NameField: "Jméno",
    SortedAscending: "Seřazeno od A do Z",
    SortedDescending: "Seřazeno Z až A",
    ModifiedField: "Datum změny",
    ModifiedByField: "Změněno",
    FileSizeField: "Velikost souboru",
    OneDriveEmptyFolderAlt: "Prázdná složka",
    OneDriveEmptyFolderDescription: "Pokud chcete přidat soubory, přejděte na OneDrive. Do této složky můžete také přidávat soubory pomocí aplikace OneDrive pro váš počítač.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Tato složka je prázdná.",
    ListLayoutAriaLabel: "Zobrazit možnosti. {0} {1} .",
    ListLayoutCompact: "Kompaktní pohled",
    ListLayoutCompactDescription: "Zobrazení položek a podrobností v kompaktním seznamu",
    ListLayoutList: "Zobrazení seznamu",
    ListLayoutListDescription: "Zobrazení položek a podrobností v seznamu",
    ListLayoutTile: "Zobrazení dlaždic",
    ListLayoutTileDescription: "Zobrazení položek s náhledy dlaždic",
    ListOptionsAlt: "Zobrazit možnosti. {0} vybrána .",
    ListOptionsTitle: "Otevření nabídky možností zobrazení",
    Selected: "vybraný",
    CategoryTranslationNotAvailable: "Překlad vybrané podkatedru není pro tento jazyk k dispozici.",
    Abandoned: "Opuštěný",
    AbandonedPlaylist: "Seznamy skladeb",
    RemoveLanguageLabel: "Odebrat jazyk",
    PropertyPaneNone: "žádný",
    WebPartModeFull: "Plný",
    WebPartModeContentOnly: "Pouze obsah",
    PropertyPaneFilterCategory: "Kategorie",
    PropertyPaneFilterSubCategory: "Podkategorie",
    PropertyPaneFilterPlaylist: "Seznam stop",
    AdminSavingNotification: "Zachraňování..",
    DataUpgradeReview: "Přezkoumání",
    DataUpgradeMultilingual: "Vícejazyčná podpora je povolena pro výukové cesty. Zkontrolujte jazyky povolené pro váš web a vypněte jazyky, které nechcete podporovat.",
    M365Title: "Výukové cesty k Microsoftu 365",
    ValidateBase: "Základní adresa URL cdn musí skončit na (/).",
    CustomizeSort: "Přizpůsobit řazení",
    ResetSort: "Obnovit řazení"
  };
});
