declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "A webrész címe (csak tartalom mód)",
    LPViewerPropertyDescription: "Egyéni tanulási tulajdonságok",
    LPViewerPropertyGroupName: "Alapértelmezett nézet",
    WebpartModeLabel: "Válassza a Kijelző mód lehetőséget",
    WebpartModeDescription: "Hogyan szeretné megjeleníteni a kijelzőt",
    ShowNavigationLabel: "Egyéni tanulási navigációs fejléc megjelenítése",
    DefaultFilterLabel: "Szűrő kiválasztása",
    DefaultFilterDescription: "Az eredmények korlátozásához jelöljön ki egy szűrőt. Egyszerre csak egy típussal szűrhet.",
    DefaultCategoryLabel: "Szűrés kategóriára",
    DefaultCategoryDescription: "Jelöljön ki egy kategóriát az eredmények korlátozásához.",
    DefaultSubCategoryLabel: "Szűrés alkategóriába",
    DefaultSubCategoryDescription: "Az eredmények korlátozásához jelöljön ki egy alkategóriát.",
    DefaultPlaylistLabel: "Szűrés lejátszási listára",
    DefaultPlaylistDescription: "Jelöljön ki egy kategóriát az eredmények korlátozásához.",
    DefaultAssetLabel: "Eszköz kiválasztása",
    DefaultAssetDescription: "Jelöljön ki egy megjeleníteni kívánt eszközt a lejátszási listából.",
    FilterPanelHeader: "Válassza ki az Önnek leginkább megfelelő tanfolyamokat",
    FilterPanelAudienceLabel: "Én vagyok a",
    FilterPanelSkillsetLabel: "Az én készségkészletem",
    NavigationHome: "Otthon",
    SearchResultItemPlayListLabel: "Lejátszási lista: ",
    SearchResultItemCategoryLabel: "Kategória: ",
    SearchPanelPlaceHolderLabel: "Lejátszási listák vagy eszközök keresése",
    LinkPanelCopyLabel: "Másolat",
    HeaderPlaylistPanelCurrentPlaylistLabel: "Aktuális lejátszási lista: ",
    HeaderPlaylistPanelAdminHeader: "Igazgatás",
    PlaylistOverviewDesignMessage: "Használat közben ez a terület más eszközöket is megjelenít a lejátszási listán, amelyben megjelenik.",
    PlaylistOverviewHeading: "A lejátszási lista minden lépése",
    BurgerButton: "Burger",
    LinkButton: "Láncszem",
    SearchButton: "Keresés",
    AdministerPlaylist: "Lejátszási lista adminisztráció",
    NoSearchResults: "Egyetlen keresési eredmény sem egyezett a lekérdezéssel.",
    DefaultCDNLabel: "Válassza a Tanulási forrás lehetőséget",
    DefaultCDNDescription: "Válassza ki a tanulási tartalom alternatív forrását.",
    DescriptionFieldLabel: "Leírás Mező",
    ImageSelectorLabel: "Kép kiválasztása",
    ImageSelectorButton: "Kép kiválasztása",
    DetailEditTitle: "Cím",
    DetailEditDescription: "Leírás",
    DetailEditUrl: "Url cím",
    DetailEditCategory: "Kategória",
    DetailEditCategoryNoData: "Nincsenek kategóriák",
    DetailEditTechnology: "Technológia",
    DetailEditLevel: "Szint",
    DetailEditAudience: "Hallgatóság",
    AssetSearchPlaceHolderLabel: "Meglévő eszközök keresése",
    CategoryHeading: "Új alkategória hozzáadása",
    CategoryHeadingLabel: "Alkategória",
    CategoryPlaylistSavedMessage: "A lejátszási lista mentésre került!",
    CategoryPlaylistSaveFailedMessage: "Nem sikerült menteni lejátszási listát!",
    CategoryNewPlayListMessage: "Módosított egy új lejátszási listát. Szeretné elvetni a változtatásokat, és folytatni?",
    CategoryEditedPlayListMessage: "Módosította ezt a lejátszási listát. Szeretné elvetni a változtatásokat, és folytatni?",
    PlaylistEditAssetSavedMessage: "Az eszközt megmentették!",
    PlaylistEditAssetSaveFailedMessage: "Nem sikerült menteni eszköz!",
    PlaylistEditCreatePlaylistHeader: "Új lejátszási lista létrehozása",
    PlaylistEditPlaylistDetailsHeader: "Lejátszási lista részletei: ",
    PlaylistEditPlaylistAssetsHeader: "Lejátszási lista eszközei",
    PlaylistEditEditLabel: "Részletek szerkesztése",
    PlaylistEditSaveLabel: "Részletek mentése",
    PlaylistEditCancelLabel: "Részletek visszavonása",
    PlaylistEditCloseLabel: "Lejátszási lista bezárása",
    AssetDetailsCreateHeader: "Új eszköz létrehozása",
    AssetDetailsManageHeader: "Egyéni eszköz kezelése:",
    AssetDetailsDetailsHeader: "Eszköz adatai: ",
    AssetDetailsSaveLabel: "Eszköz mentése",
    AssetDetailsCancelLabel: "Eszköz törlése",
    AssetDetailsCloseLabel: "Eszköz bezárása",
    AssetDetailsOpenPage: "Oldal megnyitása",
    TechnologyHeadingLabel: "Technológia",
    SubcategoryHeadingLabel: "Alkategória címsor",
    PlaylistItemPlaylistHeadingLabel: "Lejátszási lista",
    PlaylistItemPlaylistDelete: "Lejátszási lista törlése",
    PlaylistEditAssetNewLabel: "Új eszköz",
    PlaylistRemove: "Eltávolítás a lejátszási listából",
    ImageSelectorImageAlt: "Egyéni lejátszási lista",
    ImageSelectorUrlPlaceholder: "Kép url-je",
    CategoryHeadingAddPlaylistToSubcategory: "Új lejátszási lista hozzáadása az alkategória",
    AdminMenuTechnologyLabel: "Technológia",
    AdminMenuCategoryLabel: "Kategória",
    Show: "Mutat",
    Hide: "Elrejt",
    Add: "Hozzáad",
    Edit: "Szerkeszt",
    CloseButton: "Bezár",
    EditButton: "Szerkeszt",
    StepButton: "Lépés",
    MoveUpButton: "Feljebb lépés",
    MoveDownButton: "Lefelé lépés",
    SaveButton: "Megment",
    CancelButton: "Érvénytelenít",
    UpdateButton: "Frissít",
    DeleteButton: "Töröl",
    DetailEditNewPageMessage: "Új eszközoldal a Webhelyoldalak könyvtárában.",
    DetailEditExistingPageMessage: "Adja meg egy meglévő oldal URL-címét.",
    DetailEditNewPageButton: "Eszközoldal létrehozása",
    DetailEditExistingPageButton: "Url megadása",
    AdminAddCdnLabel: "Tartalomcsomag hozzáadása",
    AdminEditCdnLabel: "Tartalomcsomag szerkesztése",
    AdminDeleteCdnLabel: "Tartalomcsomag törlése",
    AdminCdnIdLabel: "Tartalomcsomag azonosítója/partnerazonosítója",
    AdminCdnDisplayName: "Megjelenítés neve",
    AdminCdnBaseUrl: "Alap URL-címe",
    AdminCustomCdnTitle: "Egyéni tartalomcsomag",
    AdminCustomCdnDescription: "Az egyéni tartalomcsomagok speciális funkciók, és csak olyan rendszergazdák használhatják, akik tapasztalattal rendelkeznek a webes tartalom adminisztrálásában. A megbízhatatlan tartalomforrások nem biztonságos tartalmat vezethetnek be webhelyére. Csak olyan forrásokat adjon hozzá, amelyekben megbízik. További információt a tanulási útvonalak dokumentációjában található Partneri útmutatóban talál.",
    AdminConfirmContentPack: "Új böngészőlap indult, amely lehetővé teszi az új tartalomcsomag biztosítását. Ha ezt sikeresen megtette, kattintson az alábbi 'Teljes' gombra az alternatív tartalomlista frissítéséhez. Ha hibát észlel, vagy úgy dönt, hogy nem telepíti a tartalomcsomagot, kattintson a 'Mégse' gombra, bármikor visszatérhet.",
    AdminCdnCompleteButton: "Teljes",
    AdminCdnCancelButton: "Érvénytelenít",
    AdminCdnSaveButton: "Megment",
    AdminCdnUpdateButton: "Frissít",
    AdminRemoveCdn: "Kérjük, erősítse meg, hogy el szeretné távolítani a kiválasztott CDN-t?",
    AdminAbout: "A webrészről",
    DocumentationLinkLabel: "M365 tanösvények dokumentációjának megnyitása",
    CategoryCopyPlaylistFail: "Sikertelen másolási lejátszási lista, kérjük, forduljon a rendszergazdához, vagy keresse fel a böngésző konzolt további részletekért.",
    PlaylistEditCopyLabel: "Lejátszási lista másolása",
    PlaylistNext: "Következő",
    PlaylistPrevious: "Előző",
    PlaylistFullScreen: "Teljes képernyős mód be váltása",
    FilterNotSet: "Összes",
    AdminVersionUpdateNotice: "A telepített Microsoft 365 tanulási útvonalak webrész elavult. Jelenleg %0% verziót futtat, a legújabb verzió pedig %1%.",
    AdminVersionUpdateInstructions: "Nézze meg a 'Megoldás frissítése' című használati utasítást.",
    AdminSecurityMessage: "Önnek nincs joga adminisztrálni a Microsoft 365 tanulási útvonalait. Kérjük, beszéljen az adminisztrátornak a Tulajdonosok vagy tagok csoporthoz való csatlakozásról.",
    AdminConfigIssueMessage: "A Microsoft 365 tanulási útvonalai konfigurációs problémát jelentenek. Kérjen segítséget az ügyintézőtől. [Rendszergazdák: A részletes naplókat lásd a böngésző konzolon. Technikai segítségnyújtásért tekintse meg a https://github.com/pnp/custom-learning-office-365/issues.]",
    AdminAwaitingUrlPrompt: "Url: Cím vár...",
    CreatingPage: "Oldal létrehozása",
    TryAgain: "Próbáld újra",
    AddLanguagePlaceholder: "Nyelv hozzáadása",
    NotApplicable: "Nem alkalmazható",
    DataUpgradeTitle: "Adatfrissítés innen:",
    DataUpgradeIntro: "Frissítette a Microsoft 365 tanulási útvonalainak jelentős új kiadását. A frissítési folyamat megkezdéséhez nyomja le a 'Start' billentyűt",
    DataUpgradeStart: "Elkezd",
    DataUpgradeClose: "Bezár",
    DataUpgradeIssue: "Ha a frissítést végző problémák merülnek fel, segítséget kérhet, ha a ",
    DataUpgradeIssueLink: "Microsoft 365 tanulási útvonalak GitHub problémalista.",
    DataUpgradeLog: "Frissítési napló",
    DataUpgradeComplete: "A frissítés befejeződött.",
    DataUpgradeErrors: "Hibák",
    LogLevel: "Szint",
    LogMessage: "Üzenet",
    AboutGroupHeader: "M365 tanulási utak",
    AboutGroupTitle: "Jelenlegi konfiguráció*",
    AboutGroupTitle2: "(* aktuális tartalomcsomag-specifikus lesz)",
    AboutLearningSiteUrl: "A tanulási webhely URL-je:",
    AboutBaseCDNPath: "A CDN alapútvonala:",
    AboutTelemetryStatus: "Telemetriai állapot:",
    AboutCurrentWPVersion: "Aktuális webrész verzió:",
    AboutMultilingualEnabled: "Többnyelvű oldalak engedélyezve:",
    AboutMultilingualLanguages: "Többnyelvű oldalak fordítási nyelvek:",
    AboutConfiguredLanguages: "Konfigurált nyelvek:",
    AboutSupportedLanguages: "Tartalomcsomag támogatott nyelvek:",
    AboutDefaultSiteLanguage: "Alapértelmezett webhelynyelv:",
    AboutCurrentUserLanguage: "Aktuális felhasználói nyelv:",
    AboutContentPackAssetOrigins: "Content Pack Eszköz eredete:",
    AboutCurrentCDN: "Jelenlegi CDN:",
    AboutAllCDNs: "Minden CDN:",
    AboutCacheLastUpdate: "Gyorsítótár utolsó frissítése:",
    DocumentLibraries: "Dokumentumtárak",
    OpenButtonLabel: "Nyitott",
    CancelButtonLabel: "Érvénytelenít",
    UploadFileHeader: "Fájl feltöltése",
    ChangeFileLinkLabel: "Fájl módosítása",
    ChooseFileLinkLabel: "Fájl kiválasztása",
    AddFileButtonLabel: "Fájl hozzáadása",
    WebSearchLinkLabel: "Webes keresés",
    CreativeCommonsMessage: "Ezek az eredmények a Creative Commons licencekkel vannak megjelölve. Tekintse át a licenceket, hogy biztosan betartsa az előírásokat.",
    CopyrightWarning: "Ön felelős mások jogainak tiszteletben tartásáért, beleértve a szerzői jogokat is.",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    LearnMoreLink: "Tudj meg többet.",
    NoResultsBadEnglish: "Nincs találat. Próbálja meg módosítani a szűrési beállításokat",
    SearchResultAlt: "Kép eredménye {0}.",
    SearchResultAriaLabel: "Nyomja le az Enter billentyűt a képforrás új lapon való megnyitásához.",
    SearchBoxPlaceholder: "Webes keresés",
    PoweredByBing: "Powered by Bing",
    SizeOptionAll: "Összes",
    SizeOptionExtraLarge: "Extra nagy",
    SizeOptionLarge: "Nagy",
    SizeOptionMedium: "Közepes",
    SizeOptionSmall: "Kicsi",
    LayoutOptionAll: "Összes",
    LayoutOptionSquare: "Négyzet",
    LayoutOptionTall: "Magas",
    LayoutOptionWide: "Széles",
    LicenseOptionAll: "Összes",
    LicenseOptionAny: "Csak a Creative Commons",
    RecentDocumentsHeader: "Legutóbbi dokumentumok",
    Loading: "Berakás...",
    NoRecentFiles: "Nincsenek friss fájlok",
    NoRecentFilesDescription: "Próbáljon ki egy fájlt a webhelyéről, vagy töltsön fel egyet az eszközéről.",
    EditedByNamePlate: "Szerkesztette ",
    LinkHeader: "Hivatkozásból",
    LinkFileInstructions: "Hivatkozás beillesztése fájlba a OneDrive Vállalati verzióban vagy SharePoint Online-ban",
    NoExternalLinksValidationMessage: "Csak a saját szervezetében lévő fájlokra való hivatkozást támogatjuk.",
    ProvidedValueIsInvalid: "A megadott érték érvénytelen",
    ImageAriaLabelTemplate: ". {0} kép",
    DocumentLabelTemplate: "{0}, Dokumentum, Módosított {1}, szerkesztette: {2}, Magán",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}, Mappa, Módosított {1}, szerkesztette: {2}, {3} elemek, Privát",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 bájt",
    SizeUnit: [
      "bytes",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "Fájlválasztó",
    OrgAssetsTabLabel: "A szervezet által biztosított képek és fájlok",
    RecentLinkLabel: "Friss",
    SiteLinkLabel: "Telephely",
    UploadLinkLabel: "Feltölt",
    FromLinkLinkLabel: "Hivatkozásból",
    TypeAriaLabel: "Oszlopműveletek a Fájltípushoz, Nyomja meg a Fájltípus rendezéséhez",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "Mappa",
    ImageAltText: ". {0} kép",
    NameField: "Név",
    SortedAscending: "A-ból Z-be rendezve",
    SortedDescending: "Z-ből A-be rendezve",
    ModifiedField: "Módosítás dátuma",
    ModifiedByField: "Módosítva:",
    FileSizeField: "Fájlméret",
    OneDriveEmptyFolderAlt: "Mappa kiürítése",
    OneDriveEmptyFolderDescription: "Fájlok hozzáadásához lépjen a OneDrive-ra. Ehhez a mappához fájlokat is hozzáadhat a számítógép OneDrive alkalmazásával.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Ez a mappa üres",
    ListLayoutAriaLabel: "Beállítások megtekintése. {0} {1} .",
    ListLayoutCompact: "Kompakt nézet",
    ListLayoutCompactDescription: "Elemek és részletek megtekintése kompakt listában",
    ListLayoutList: "Lista nézet",
    ListLayoutListDescription: "Elemek és részletek megtekintése egy listában",
    ListLayoutTile: "Csempe nézet",
    ListLayoutTileDescription: "Elemek megtekintése csempe előnézetekkel",
    ListOptionsAlt: "Beállítások megtekintése. {0} kiválasztva .",
    ListOptionsTitle: "A nézetbeállítások menü megnyitása",
    Selected: "kiválasztott",
    CategoryTranslationNotAvailable: "A kiválasztott alkategória fordítása nem érhető el ehhez a nyelvhez.",
    Abandoned: "Elhagyott",
    AbandonedPlaylist: "Lejátszási listák",
    RemoveLanguageLabel: "Nyelv eltávolítása",
    PropertyPaneNone: "egyik sem",
    WebPartModeFull: "Tele",
    WebPartModeContentOnly: "Csak tartalom",
    PropertyPaneFilterCategory: "Kategória",
    PropertyPaneFilterSubCategory: "Alkategória",
    PropertyPaneFilterPlaylist: "Lejátszási lista",
    AdminSavingNotification: "Megtakarítás..",
    DataUpgradeReview: "Szemle",
    DataUpgradeMultilingual: "A többnyelvű támogatás lehetővé teszi a tanulási útvonalakat. Tekintse át a webhely számára engedélyezett nyelveket, és kapcsolja ki azokat a nyelveket, amelyeket nem szeretne támogatni.",
    M365Title: "Microsoft 365 tanulási útvonalak",
    ValidateBase: "A CDN alap url-jének (/) végződnie kell.",
    CustomizeSort: "Rendezés testreszabása",
    ResetSort: "Rendezés alaphelyzetbe állítása"
  };
});
