declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Tytuł składnika Web Part (tryb tylko zawartość)",
    LPViewerPropertyDescription: "Niestandardowe właściwości edukacyjne",
    LPViewerPropertyGroupName: "Widok domyślny",
    WebpartModeLabel: "Wybieranie trybu składników Web Part",
    WebpartModeDescription: "Jak ma być wyświetlany składnik Web Part",
    ShowNavigationLabel: "Pokaż niestandardowy nagłówek nawigacji edukacyjnej",
    DefaultFilterLabel: "Wybierz filtr",
    DefaultFilterDescription: "Wybierz filtr, aby ograniczyć wyniki. Filtrować można tylko według jednego typu naraz.",
    DefaultCategoryLabel: "Filtruj według kategorii",
    DefaultCategoryDescription: "Wybierz kategorię, aby ograniczyć wyniki.",
    DefaultSubCategoryLabel: "Filtruj według podkategorii",
    DefaultSubCategoryDescription: "Wybierz podkategorię, aby ograniczyć wyniki.",
    DefaultPlaylistLabel: "Filtruj do listy odtwarzania",
    DefaultPlaylistDescription: "Wybierz kategorię, aby ograniczyć wyniki.",
    DefaultAssetLabel: "Wybierz zasób",
    DefaultAssetDescription: "Wybierz zasób do wyświetlenia z listy odtwarzania.",
    FilterPanelHeader: "Wybierz kursy, które najbardziej Ci odpowiadają",
    FilterPanelAudienceLabel: "Jestem",
    FilterPanelSkillsetLabel: "Mój zestaw umiejętności to",
    NavigationHome: "Dom",
    SearchResultItemPlayListLabel: "Lista odtwarzania: ",
    SearchResultItemCategoryLabel: "Kategoria: ",
    SearchPanelPlaceHolderLabel: "Wyszukiwanie playlist lub zasobów",
    LinkPanelCopyLabel: "Kopiować",
    HeaderPlaylistPanelCurrentPlaylistLabel: "Aktualna lista odtwarzania: ",
    HeaderPlaylistPanelAdminHeader: "Administracja",
    PlaylistOverviewDesignMessage: "Podczas korzystania ten obszar będzie pokazywał inne zasoby na liście odtwarzania, na której jest wyświetlany.",
    PlaylistOverviewHeading: "Wszystkie kroki na liście odtwarzania",
    BurgerButton: "Hamburger",
    LinkButton: "Łącze",
    SearchButton: "Szukać",
    AdministerPlaylist: "Administracja listą odtwarzania",
    NoSearchResults: "Żadne wyniki wyszukiwania nie pasują do Twojego zapytania.",
    DefaultCDNLabel: "Wybierz źródło informacji",
    DefaultCDNDescription: "Wybierz alternatywne źródło treści edukacyjnych.",
    DescriptionFieldLabel: "Pole opisu",
    ImageSelectorLabel: "Wybierz obraz",
    ImageSelectorButton: "Wybierz obraz",
    DetailEditTitle: "Tytuł",
    DetailEditDescription: "Opis",
    DetailEditUrl: "Adres URL",
    DetailEditCategory: "Kategoria",
    DetailEditCategoryNoData: "Brak dostępnych kategorii",
    DetailEditTechnology: "Technologia",
    DetailEditLevel: "Poziom",
    DetailEditAudience: "Audiencja",
    AssetSearchPlaceHolderLabel: "Wyszukiwanie istniejących zasobów",
    CategoryHeading: "Dodaj nową podkategorię",
    CategoryHeadingLabel: "Podkategorii",
    CategoryPlaylistSavedMessage: "Playlista została zapisana!",
    CategoryPlaylistSaveFailedMessage: "Nie udało się zapisać listy odtwarzania!",
    CategoryNewPlayListMessage: "Wprowadzono zmiany w nowej liście odtwarzania. Czy chcesz odrzucić swoje zmiany i kontynuować?",
    CategoryEditedPlayListMessage: "Wprowadzono zmiany na tej liście odtwarzania. Czy chcesz odrzucić swoje zmiany i kontynuować?",
    PlaylistEditAssetSavedMessage: "Zasób został uratowany!",
    PlaylistEditAssetSaveFailedMessage: "Nie udało się uratować zasobu!",
    PlaylistEditCreatePlaylistHeader: "Tworzenie nowej listy odtwarzania",
    PlaylistEditPlaylistDetailsHeader: "Szczegóły listy odtwarzania: ",
    PlaylistEditPlaylistAssetsHeader: "Zasoby playlist",
    PlaylistEditEditLabel: "Edytuj szczegóły",
    PlaylistEditSaveLabel: "Zapisz szczegóły",
    PlaylistEditCancelLabel: "Anuluj szczegóły",
    PlaylistEditCloseLabel: "Zamknij listę odtwarzania",
    AssetDetailsCreateHeader: "Tworzenie nowego zasobu",
    AssetDetailsManageHeader: "Zarządzanie zasobami niestandardowymi:",
    AssetDetailsDetailsHeader: "Szczegóły zasobu: ",
    AssetDetailsSaveLabel: "Zapisz zasób",
    AssetDetailsCancelLabel: "Anuluj zasób",
    AssetDetailsCloseLabel: "Zamknij zasób",
    AssetDetailsOpenPage: "Otwórz stronę",
    TechnologyHeadingLabel: "Technologia",
    SubcategoryHeadingLabel: "Nagłówek podkategorii",
    PlaylistItemPlaylistHeadingLabel: "Lista odtwarzania",
    PlaylistItemPlaylistDelete: "Usuń listę odtwarzania",
    PlaylistEditAssetNewLabel: "Nowy zasób",
    PlaylistRemove: "Usuń z listy odtwarzania",
    ImageSelectorImageAlt: "Niestandardowa lista odtwarzania",
    ImageSelectorUrlPlaceholder: "Adres URL obrazu",
    CategoryHeadingAddPlaylistToSubcategory: "Dodaj nową listę odtwarzania do podkategorii",
    AdminMenuTechnologyLabel: "Technologia",
    AdminMenuCategoryLabel: "Kategoria",
    Show: "Pokazać",
    Hide: "Ukrywać",
    Add: "Dodawać",
    Edit: "Redagować",
    CloseButton: "Zamykać",
    EditButton: "Redagować",
    StepButton: "Krok",
    MoveUpButton: "Przenieś się w górę",
    MoveDownButton: "Przesuń w dół",
    SaveButton: "Zapisać",
    CancelButton: "Anuluj",
    UpdateButton: "Aktualizacja",
    DeleteButton: "Usunąć",
    DetailEditNewPageMessage: "Nowa strona zasobu w bibliotece Stron witryny.",
    DetailEditExistingPageMessage: "Wprowadź adres URL istniejącej strony.",
    DetailEditNewPageButton: "Utwórz stronę zasobu",
    DetailEditExistingPageButton: "Wpisz adres URL",
    AdminAddCdnLabel: "Dodaj pakiet zawartości",
    AdminEditCdnLabel: "Edytuj pakiet zawartości",
    AdminDeleteCdnLabel: "Usuń pakiet zawartości",
    AdminCdnIdLabel: "Identyfikator pakietu zawartości/identyfikator partnera",
    AdminCdnDisplayName: "Nazwa wyświetlana",
    AdminCdnBaseUrl: "Podstawowy adres URL",
    AdminCustomCdnTitle: "Niestandardowy pakiet zawartości",
    AdminCustomCdnDescription: "Niestandardowe pakiety zawartości są funkcją zaawansowaną i powinny być używane tylko przez administratorów z doświadczeniem w administrowaniu zawartością sieci Web. Niewiarygodne źródła treści mogą wprowadzać niebezpieczne treści do Witryny. Należy dodawać tylko te źródła, którym ufasz. Aby uzyskać więcej informacji, zobacz Wskazówki dla partnerów w dokumentacji ścieżek szkoleniowych.",
    AdminConfirmContentPack: "Uruchomiono nową kartę przeglądarki, która umożliwi aprowizowanie nowego pakietu zawartości. Po pomyślnym wykonaniu tej czynności kliknij 'Zakończ' poniżej, aby zaktualizować alternatywną listę zawartości. Jeśli wystąpi błąd lub zdecydujesz się nie instalować pakietu zawartości, kliknij 'Anuluj', możesz wrócić w dowolnym momencie.",
    AdminCdnCompleteButton: "Ukończyć",
    AdminCdnCancelButton: "Anuluj",
    AdminCdnSaveButton: "Zapisać",
    AdminCdnUpdateButton: "Aktualizacja",
    AdminRemoveCdn: "Potwierdź, że chcesz usunąć wybraną cdn?",
    AdminAbout: "Informacje o składniku Web Part",
    DocumentationLinkLabel: "Otwarta dokumentacja ścieżek szkoleniowych M365",
    CategoryCopyPlaylistFail: "Nie powiodło się kopiowanie listy odtwarzania, skontaktuj się z administratorem lub zobacz konsolę przeglądarki, aby uzyskać więcej informacji.",
    PlaylistEditCopyLabel: "Kopiuj listę odtwarzania",
    PlaylistNext: "Następny",
    PlaylistPrevious: "Poprzedni",
    PlaylistFullScreen: "Przełączanie trybu pełnoekranowego",
    FilterNotSet: "Cały",
    AdminVersionUpdateNotice: "Zainstalowany składnik Web Part Ścieżek szkoleniowych platformy Microsoft 365 jest nieaktualny. Obecnie korzystasz z wersji %0%, a najnowsza wersja to %1%.",
    AdminVersionUpdateInstructions: "Zapoznaj się z instrukcjami dotyczącymi 'Aktualizowania rozwiązania'.",
    AdminSecurityMessage: "Nie masz praw do administrowania ścieżkami szkoleniowymi platformy Microsoft 365. Porozmawiaj z administratorem o dołączeniu do grupy Właściciele lub Członkowie.",
    AdminConfigIssueMessage: "Ścieżka szkoleniowa platformy Microsoft 365 ma problem z konfiguracją. Poproś administratora o pomoc. [Administratorzy: Szczegółowe dzienniki można znaleźć w konsoli przeglądarki. Aby uzyskać pomoc techniczną, zapoznaj się z listą problemów na stronie https://github.com/pnp/custom-learning-office-365/issues.]",
    AdminAwaitingUrlPrompt: "Url: Oczekiwanie na tytuł...",
    CreatingPage: "Tworzenie strony",
    TryAgain: "Spróbuj ponownie",
    AddLanguagePlaceholder: "Dodaj język",
    NotApplicable: "Nie dotyczy",
    DataUpgradeTitle: "Uaktualnianie danych z",
    DataUpgradeIntro: "Zaktualizowano do nowej, głównej wersji ścieżek szkoleniowych platformy Microsoft 365. Aby rozpocząć proces aktualizacji, naciśnij 'Start'",
    DataUpgradeStart: "Początek",
    DataUpgradeClose: "Zamykać",
    DataUpgradeIssue: "Jeśli wystąpią problemy z wykonaniem aktualizacji, możesz poprosić o pomoc, przesyłając problem do ",
    DataUpgradeIssueLink: "Microsoft 365 learning pathways GitHub issue list.",
    DataUpgradeLog: "Dziennik uaktualnień",
    DataUpgradeComplete: "Uaktualnienie zostało zakończone.",
    DataUpgradeErrors: "Błędy",
    LogLevel: "Poziom",
    LogMessage: "Komunikat",
    AboutGroupHeader: "Ścieżki uczenia się M365",
    AboutGroupTitle: "Bieżąca konfiguracja*",
    AboutGroupTitle2: "(* będzie specyficzny dla bieżącego pakietu zawartości)",
    AboutLearningSiteUrl: "Adres URL witryny edukacyjnej:",
    AboutBaseCDNPath: "Podstawowa ścieżka CDN:",
    AboutTelemetryStatus: "Stan telemetrii:",
    AboutCurrentWPVersion: "Bieżąca wersja składnika Web Part:",
    AboutMultilingualEnabled: "Włączone strony wielojęzyczne:",
    AboutMultilingualLanguages: "Wielojęzyczne języki tłumaczenia stron:",
    AboutConfiguredLanguages: "Skonfigurowane języki:",
    AboutSupportedLanguages: "Obsługiwane języki pakietu zawartości:",
    AboutDefaultSiteLanguage: "Domyślny język witryny:",
    AboutCurrentUserLanguage: "Bieżący język użytkownika:",
    AboutContentPackAssetOrigins: "Pochodzenie zasobów z pakietu zawartości:",
    AboutCurrentCDN: "Aktualna cdn:",
    AboutAllCDNs: "Wszystkie cdn:",
    AboutCacheLastUpdate: "Ostatnia aktualizacja pamięci podręcznej:",
    DocumentLibraries: "Biblioteki dokumentów",
    OpenButtonLabel: "Otwierać",
    CancelButtonLabel: "Anuluj",
    UploadFileHeader: "Prześlij plik",
    ChangeFileLinkLabel: "Zmień plik",
    ChooseFileLinkLabel: "Wybierz plik",
    AddFileButtonLabel: "Dodaj plik",
    WebSearchLinkLabel: "Wyszukiwanie w Internecie",
    CreativeCommonsMessage: "Wyniki te są oznaczone licencjami Creative Commons. Przejrzyj licencje, aby upewnić się, że są zgodne.",
    CopyrightWarning: "Użytkownik jest odpowiedzialny za poszanowanie praw innych osób, w tym praw autorskich.",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    LearnMoreLink: "Dowiedz się więcej.",
    NoResultsBadEnglish: "Nie znaleziono wyniku. Spróbuj zmienić opcje filtrowania",
    SearchResultAlt: "Wynik obrazu dla {0}.",
    SearchResultAriaLabel: "Naciśnij Enter, aby otworzyć źródło obrazu w nowej karcie.",
    SearchBoxPlaceholder: "Wyszukiwanie w Internecie",
    PoweredByBing: "Obsługiwane przez Bing",
    SizeOptionAll: "Cały",
    SizeOptionExtraLarge: "Bardzo duży",
    SizeOptionLarge: "Duży",
    SizeOptionMedium: "Średni",
    SizeOptionSmall: "Mały",
    LayoutOptionAll: "Cały",
    LayoutOptionSquare: "Kwadratowy",
    LayoutOptionTall: "Wysoki",
    LayoutOptionWide: "Szeroki",
    LicenseOptionAll: "Cały",
    LicenseOptionAny: "Tylko Creative Commons",
    RecentDocumentsHeader: "Ostatnie dokumenty",
    Loading: "Ładowania...",
    NoRecentFiles: "Brak ostatnio używanych plików",
    NoRecentFilesDescription: "Spróbuj wybrać plik z witryny lub przesłać go z urządzenia.",
    EditedByNamePlate: "edytowane przez ",
    LinkHeader: "Z linku",
    LinkFileInstructions: "Wklejanie łącza do pliku w usłudze OneDrive dla Firm lub sharePoint Online",
    NoExternalLinksValidationMessage: "Obsługujemy tylko łączenie z plikami w Twojej organizacji.",
    ProvidedValueIsInvalid: "Podana wartość jest nieprawidłowa",
    ImageAriaLabelTemplate: ". Obraz {0}",
    DocumentLabelTemplate: "{0}, Dokument, Zmodyfikowane {1}, Edytowane przez {2}, Prywatne",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}, Folder, Zmodyfikowane {1}, Edytowane przez {2}, Elementy {3}, Prywatne",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 bajtów",
    SizeUnit: [
      "bytes",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "Selektor plików",
    OrgAssetsTabLabel: "Obrazy i pliki dostarczone przez organizację",
    RecentLinkLabel: "Niedawny",
    SiteLinkLabel: "Miejsce",
    UploadLinkLabel: "Przesyłać",
    FromLinkLinkLabel: "Z linku",
    TypeAriaLabel: "Operacje kolumnowe dla Typ pliku, Naciśnij, aby sortować według typu pliku",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "Folder",
    ImageAltText: ". Obraz {0}",
    NameField: "Nazwa",
    SortedAscending: "Posortowane od A do Z",
    SortedDescending: "Posortowane Z do A",
    ModifiedField: "Data modyfikacji",
    ModifiedByField: "Zmodyfikowane przez",
    FileSizeField: "Rozmiar pliku",
    OneDriveEmptyFolderAlt: "Pusty folder",
    OneDriveEmptyFolderDescription: "Aby dodać pliki, przejdź do usługi OneDrive. Możesz także dodawać pliki do tego folderu za pomocą aplikacji OneDrive na komputerze.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Ten folder jest pusty",
    ListLayoutAriaLabel: "Opcje wyświetlania. {0} {1} .",
    ListLayoutCompact: "Kompaktowy widok",
    ListLayoutCompactDescription: "Wyświetlanie elementów i szczegółów na liście kompaktowej",
    ListLayoutList: "Widok listy",
    ListLayoutListDescription: "Wyświetlanie elementów i szczegółów na liście",
    ListLayoutTile: "Widok kafelków",
    ListLayoutTileDescription: "Wyświetlanie elementów za pomocą podglądu kafelków",
    ListOptionsAlt: "Opcje wyświetlania. {0} wybrano .",
    ListOptionsTitle: "Otwieranie menu opcji widoku",
    Selected: "wybrany",
    CategoryTranslationNotAvailable: "Tłumaczenie wybranej podkategorii nie jest dostępne dla tego języka.",
    Abandoned: "Opuszczony",
    AbandonedPlaylist: "Listy odtwarzania",
    RemoveLanguageLabel: "Usuń język",
    PropertyPaneNone: "żaden",
    WebPartModeFull: "Pełny",
    WebPartModeContentOnly: "Tylko treść",
    PropertyPaneFilterCategory: "Kategoria",
    PropertyPaneFilterSubCategory: "Podkategoria",
    PropertyPaneFilterPlaylist: "Lista odtwarzania",
    AdminSavingNotification: "Oszczędność..",
    DataUpgradeReview: "Recenzja",
    DataUpgradeMultilingual: "Wielojęzyczne wsparcie jest włączone dla ścieżek uczenia się. Przejrzyj języki włączone w witrynie i wyłącz języki, których nie chcesz obsługiwać.",
    M365Title: "Ścieżki edukacyjne dotyczące platformy Microsoft 365",
    ValidateBase: "Podstawowy adres URL sieci CDN musi kończyć się na (/).",
    CustomizeSort: "Dostosuj sortowanie",
    ResetSort: "Resetowanie sortowania"
  };
});
