declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Titlul părții web (modul numai conținut)",
    LPViewerPropertyDescription: "Proprietăți de învățare personalizate",
    LPViewerPropertyGroupName: "Vizualizare implicită",
    WebpartModeLabel: "Selectați modul parte web",
    WebpartModeDescription: "Cum doriți să afișați partea web",
    ShowNavigationLabel: "Afișare antet de navigare de învățare particularizată",
    DefaultFilterLabel: "Selectați un filtru",
    DefaultFilterDescription: "Selectați un filtru pentru a limita rezultatele. Puteți filtra doar după un singur tip la un moment dat.",
    DefaultCategoryLabel: "Filtrare la categorie",
    DefaultCategoryDescription: "Selectați o categorie pentru a limita rezultatele.",
    DefaultSubCategoryLabel: "Filtrarea în subcategorie",
    DefaultSubCategoryDescription: "Selectați o subcategorie pentru a limita rezultatele.",
    DefaultPlaylistLabel: "Filtrați în playlist",
    DefaultPlaylistDescription: "Selectați o categorie pentru a limita rezultatele.",
    DefaultAssetLabel: "Selectați un activ",
    DefaultAssetDescription: "Selectează un material de afișat din lista de redare.",
    FilterPanelHeader: "Alege cursurile care ti se potrivesc cel mai bine",
    FilterPanelAudienceLabel: "Eu sunt un",
    FilterPanelSkillsetLabel: "Setul meu de abilități este",
    NavigationHome: "Domiciliu",
    SearchResultItemPlayListLabel: "Redare: ",
    SearchResultItemCategoryLabel: "Categorie: ",
    SearchPanelPlaceHolderLabel: "Caută liste de redare sau active",
    LinkPanelCopyLabel: "Copie",
    HeaderPlaylistPanelCurrentPlaylistLabel: "Lista de redare curentă: ",
    HeaderPlaylistPanelAdminHeader: "Administrație",
    PlaylistOverviewDesignMessage: "În timpul utilizării, această zonă va afișa alte active în lista de redare în care este afișată.",
    PlaylistOverviewHeading: "Toți pașii din lista de redare",
    BurgerButton: "Burger",
    LinkButton: "Legătură",
    SearchButton: "Căutare",
    AdministerPlaylist: "Administrare playlist",
    NoSearchResults: "Niciun rezultat al căutării nu corespundea interogării dvs.",
    DefaultCDNLabel: "Selectați Sursa de învățare",
    DefaultCDNDescription: "Selectați o sursă alternativă pentru învățarea conținutului.",
    DescriptionFieldLabel: "Câmp descriere",
    ImageSelectorLabel: "Alegeți o imagine",
    ImageSelectorButton: "Alege Imagine",
    DetailEditTitle: "Titlu",
    DetailEditDescription: "Descriere",
    DetailEditUrl: "URL-ul",
    DetailEditCategory: "Categorie",
    DetailEditCategoryNoData: "Nu sunt disponibile categorii",
    DetailEditTechnology: "Tehnologie",
    DetailEditLevel: "Nivel",
    DetailEditAudience: "Audiență",
    AssetSearchPlaceHolderLabel: "Căutarea activelor existente",
    CategoryHeading: "Adăugarea unei subcategorii noi",
    CategoryHeadingLabel: "Subcategorie",
    CategoryPlaylistSavedMessage: "Playlist-ul a fost salvat!",
    CategoryPlaylistSaveFailedMessage: "Nu a reușit să salveze lista de redare!",
    CategoryNewPlayListMessage: "Ai făcut modificări într-o nouă listă de redare. Doriți să renunțați la modificări și să continuați?",
    CategoryEditedPlayListMessage: "Ați făcut modificări la această listă de redare. Doriți să renunțați la modificări și să continuați?",
    PlaylistEditAssetSavedMessage: "Activul a fost salvat!",
    PlaylistEditAssetSaveFailedMessage: "Nu a reușit să salveze activul!",
    PlaylistEditCreatePlaylistHeader: "Creează o listă de redare nouă",
    PlaylistEditPlaylistDetailsHeader: "Detalii playlist: ",
    PlaylistEditPlaylistAssetsHeader: "Active playlist",
    PlaylistEditEditLabel: "Editare detalii",
    PlaylistEditSaveLabel: "Salvare detalii",
    PlaylistEditCancelLabel: "Anulare detalii",
    PlaylistEditCloseLabel: "Închideți lista de redare",
    AssetDetailsCreateHeader: "Crearea unui activ nou",
    AssetDetailsManageHeader: "Gestionați activul personalizat:",
    AssetDetailsDetailsHeader: "Detalii activ: ",
    AssetDetailsSaveLabel: "Salvați activul",
    AssetDetailsCancelLabel: "Anulare activ",
    AssetDetailsCloseLabel: "Închideți activul",
    AssetDetailsOpenPage: "Deschide pagina",
    TechnologyHeadingLabel: "Tehnologie",
    SubcategoryHeadingLabel: "Titlu subcategorie",
    PlaylistItemPlaylistHeadingLabel: "Redare",
    PlaylistItemPlaylistDelete: "Ștergeți lista de redare",
    PlaylistEditAssetNewLabel: "Activ nou",
    PlaylistRemove: "Eliminați din lista de redare",
    ImageSelectorImageAlt: "Listă de redare personalizată",
    ImageSelectorUrlPlaceholder: "Url imagine",
    CategoryHeadingAddPlaylistToSubcategory: "Adăugarea unei liste de redare noi la Subcategorie",
    AdminMenuTechnologyLabel: "Tehnologie",
    AdminMenuCategoryLabel: "Categorie",
    Show: "Arăta",
    Hide: "Ascunde",
    Add: "Adăuga",
    Edit: "Editare",
    CloseButton: "Închide",
    EditButton: "Editare",
    StepButton: "Treaptă",
    MoveUpButton: "Mutare în sus",
    MoveDownButton: "Mutare în jos",
    SaveButton: "Salva",
    CancelButton: "Anula",
    UpdateButton: "Actualiza",
    DeleteButton: "Șterge",
    DetailEditNewPageMessage: "Pagină de active noi în biblioteca Pagini site.",
    DetailEditExistingPageMessage: "Introduceți URL-ul unei pagini existente.",
    DetailEditNewPageButton: "Creează o pagină de activ",
    DetailEditExistingPageButton: "Introduceți URL-ul",
    AdminAddCdnLabel: "Adăugarea pachetului de conținut",
    AdminEditCdnLabel: "Editarea pachetului de conținut",
    AdminDeleteCdnLabel: "Ștergerea pachetului de conținut",
    AdminCdnIdLabel: "Id-ul pachetului de conținut/ID-ul partenerului",
    AdminCdnDisplayName: "Nume afișat",
    AdminCdnBaseUrl: "URL-ul de bază",
    AdminCustomCdnTitle: "Pachet de conținut personalizat",
    AdminCustomCdnDescription: "Pachetele de conținut personalizate sunt o caracteristică avansată și ar trebui să fie utilizate numai de către administratorii cu experiență în administrarea conținutului web. Sursele de conținut nedemne de încredere pot introduce conținut nesigur în site-ul dvs. Ar trebui să adăugați doar surse în care aveți încredere. Pentru mai multe informații, consultați Ghidarea partenerilor în documentația căilor de învățare.",
    AdminConfirmContentPack: "A fost pornită o nouă filă de browser care vă va permite să furnizați noul pachet de conținut. După ce ați făcut acest lucru cu succes, faceți clic pe 'Finalizare' de mai jos pentru a actualiza lista de conținut alternativ. Dacă aveți o eroare sau alegeți să nu instalați pachetul de conținut, faceți clic pe 'Anulare', puteți reveni în orice moment.",
    AdminCdnCompleteButton: "Complet",
    AdminCdnCancelButton: "Anula",
    AdminCdnSaveButton: "Salva",
    AdminCdnUpdateButton: "Actualiza",
    AdminRemoveCdn: "Vă rugăm să confirmați că doriți să eliminați CDN-ul selectat?",
    AdminAbout: "Despre partea web",
    DocumentationLinkLabel: "Deschideți documentația căilor de învățare M365",
    CategoryCopyPlaylistFail: "Nu a reușit copierea listei de redare, vă rugăm să contactați administratorul sau să consultați consola browser-ului pentru mai multe detalii.",
    PlaylistEditCopyLabel: "Copiați lista de redare",
    PlaylistNext: "Următor",
    PlaylistPrevious: "Precedent",
    PlaylistFullScreen: "Comutarea modului ecran complet",
    FilterNotSet: "Tot",
    AdminVersionUpdateNotice: "Partea web căi de învățare Microsoft 365 instalată este depășită. În prezent, executați versiunea %0%, iar cea mai nouă versiune este %1%.",
    AdminVersionUpdateInstructions: "Consultați instrucțiunile pentru 'Actualizarea soluției'.",
    AdminSecurityMessage: "Nu aveți dreptul de a administra căile de învățare Microsoft 365. Vă rugăm să discutați cu administratorul despre aderarea la proprietari sau membri grup.",
    AdminConfigIssueMessage: "Căile de învățare Microsoft 365 au o problemă de configurare. Solicitați asistență administratorului. [Administratori: Consultați consola browserului pentru jurnale detaliate. Pentru asistență tehnică consultați lista de probleme de la https://github.com/pnp/custom-learning-office-365/issues.]",
    AdminAwaitingUrlPrompt: "Url: În așteptarea titlului ...",
    CreatingPage: "Crearea paginii",
    TryAgain: "Încearcă din nou",
    AddLanguagePlaceholder: "Adăugarea limbii",
    NotApplicable: "Nu se aplică",
    DataUpgradeTitle: "Upgrade de date de la",
    DataUpgradeIntro: "Ați actualizat la o nouă versiune majoră de căi de învățare Microsoft 365. Pentru a începe procesul de upgrade apăsați pe 'Start'",
    DataUpgradeStart: "Porni",
    DataUpgradeClose: "Închide",
    DataUpgradeIssue: "Dacă întâmpinați probleme la efectuarea actualizării, puteți solicita asistență trimițând o problemă la ",
    DataUpgradeIssueLink: "Lista de probleme Microsoft 365 learning pathways GitHub.",
    DataUpgradeLog: "Jurnal de upgrade",
    DataUpgradeComplete: "Upgrade-ul s-a finalizat.",
    DataUpgradeErrors: "Erori",
    LogLevel: "Nivel",
    LogMessage: "Mesaj",
    AboutGroupHeader: "Căi de învățare M365",
    AboutGroupTitle: "Configurație curentă*",
    AboutGroupTitle2: "(* va fi pachetul de conținut curent specific)",
    AboutLearningSiteUrl: "Url-ul site-ului de învățare:",
    AboutBaseCDNPath: "Calea CDN de bază:",
    AboutTelemetryStatus: "Starea telemetriei:",
    AboutCurrentWPVersion: "Versiunea curentă a părții web:",
    AboutMultilingualEnabled: "Pagini multilingve activate:",
    AboutMultilingualLanguages: "Limbi de traducere pagini multilingve:",
    AboutConfiguredLanguages: "Limbi configurate:",
    AboutSupportedLanguages: "Pachete de conținut Limbi acceptate:",
    AboutDefaultSiteLanguage: "Limba implicită a site-ului:",
    AboutCurrentUserLanguage: "Limba curentă a utilizatorului:",
    AboutContentPackAssetOrigins: "Content Pack Asset Origins:",
    AboutCurrentCDN: "CDN curent:",
    AboutAllCDNs: "Toate CDN-urile:",
    AboutCacheLastUpdate: "Cache Ultima actualizare:",
    DocumentLibraries: "Biblioteci de documente",
    OpenButtonLabel: "Deschide",
    CancelButtonLabel: "Anula",
    UploadFileHeader: "Încărcați fișierul",
    ChangeFileLinkLabel: "Modificarea fișierului",
    ChooseFileLinkLabel: "Alegeți fișierul",
    AddFileButtonLabel: "Adăugarea fișierului",
    WebSearchLinkLabel: "Căutare pe web",
    CreativeCommonsMessage: "Aceste rezultate sunt etichetate cu licențe Creative Commons. Examinați licențele pentru a vă asigura că vă conformați.",
    CopyrightWarning: "Sunteți responsabil pentru respectarea drepturilor altora, inclusiv a drepturilor de autor.",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    LearnMoreLink: "Află mai multe.",
    NoResultsBadEnglish: "Nu se găsește niciun rezultat. Încercați să modificați opțiunile de filtrare",
    SearchResultAlt: "Rezultatul imaginii pentru {0}.",
    SearchResultAriaLabel: "Apăsați enter pentru a deschide sursa imaginii într-o filă nouă.",
    SearchBoxPlaceholder: "Căutare pe web",
    PoweredByBing: "Realizat de Bing",
    SizeOptionAll: "Tot",
    SizeOptionExtraLarge: "Extra mare",
    SizeOptionLarge: "Mare",
    SizeOptionMedium: "Medie",
    SizeOptionSmall: "Mic",
    LayoutOptionAll: "Tot",
    LayoutOptionSquare: "Pătrat",
    LayoutOptionTall: "Înalt",
    LayoutOptionWide: "Larg",
    LicenseOptionAll: "Tot",
    LicenseOptionAny: "Creative Commons numai",
    RecentDocumentsHeader: "Documente recente",
    Loading: "Încărcare...",
    NoRecentFiles: "Fără fișiere recente",
    NoRecentFilesDescription: "Încercați să selectați un fișier de pe site sau să încărcați unul de pe dispozitiv.",
    EditedByNamePlate: "editat de ",
    LinkHeader: "Dintr-un link",
    LinkFileInstructions: "Lipirea unui link la un fișier în OneDrive pentru business sau SharePoint Online",
    NoExternalLinksValidationMessage: "Acceptăm doar conectarea la fișiere din propria organizație.",
    ProvidedValueIsInvalid: "Valoarea furnizată nu este validă",
    ImageAriaLabelTemplate: ". {0} Imagine",
    DocumentLabelTemplate: "{0}, Document, {1} modificat, editat de {2}, Privat",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}, Folder, Modificat {1}, editat de {2}, elemente {3}, Privat",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 octeți",
    SizeUnit: [
      "bytes",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "Selector de fișiere",
    OrgAssetsTabLabel: "Imagini și fișiere furnizate de organizația dvs.",
    RecentLinkLabel: "Recent",
    SiteLinkLabel: "Site",
    UploadLinkLabel: "Încărca",
    FromLinkLinkLabel: "Dintr-un link",
    TypeAriaLabel: "Operațiuni de coloană pentru Tipul de fișier, Apăsați pentru a sorta pe Tipul de fișier",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "Dosar",
    ImageAltText: ". {0} Imagine",
    NameField: "Nume",
    SortedAscending: "Sortate de la A la Z",
    SortedDescending: "Sortate de la Z la A",
    ModifiedField: "Data modificării",
    ModifiedByField: "Modificat de",
    FileSizeField: "Dimensiune fișier",
    OneDriveEmptyFolderAlt: "Folder gol",
    OneDriveEmptyFolderDescription: "Pentru a adăuga fișiere, accesați OneDrive. De asemenea, puteți adăuga fișiere în acest folder utilizând aplicația OneDrive pentru computer.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Acest folder este gol",
    ListLayoutAriaLabel: "Opțiuni de vizualizare. {0} {1} .",
    ListLayoutCompact: "Vizualizare compactă",
    ListLayoutCompactDescription: "Vizualizarea elementelor și detaliilor într-o listă compactă",
    ListLayoutList: "Vizualizare listă",
    ListLayoutListDescription: "Vizualizarea elementelor și detaliilor dintr-o listă",
    ListLayoutTile: "Vizualizarea dale",
    ListLayoutTileDescription: "Vizualizarea elementelor cu previzualizări pentru dale",
    ListOptionsAlt: "Opțiuni de vizualizare. {0} selectat .",
    ListOptionsTitle: "Deschiderea meniului de opțiuni pentru vizualizare",
    Selected: "Selectat",
    CategoryTranslationNotAvailable: "O traducere a subcategorii selectate nu este disponibilă pentru această limbă.",
    Abandoned: "Abandonat",
    AbandonedPlaylist: "Liste de redare",
    RemoveLanguageLabel: "Eliminați limba",
    PropertyPaneNone: "niciunul",
    WebPartModeFull: "Plin",
    WebPartModeContentOnly: "Numai conținut",
    PropertyPaneFilterCategory: "Categorie",
    PropertyPaneFilterSubCategory: "Subcategorie",
    PropertyPaneFilterPlaylist: "Redare",
    AdminSavingNotification: "Economisire..",
    DataUpgradeReview: "Recenzie",
    DataUpgradeMultilingual: "Suportul multilingv este permis pentru parcursurile de învățare. Examinați limbile activate pentru site și dezactivați limbile pe care nu doriți să le susțineți.",
    M365Title: "Căi de învățare Microsoft 365",
    ValidateBase: "URL-ul de bază pentru CDN trebuie să se termine într-un (/).",
    CustomizeSort: "Particularizarea sortului",
    ResetSort: "Resetare sortare"
  };
});
