declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Názov webovej časti (iba režim obsahu)",
    LPViewerPropertyDescription: "Vlastné vlastnosti učenia",
    LPViewerPropertyGroupName: "Predvolené zobrazenie",
    WebpartModeLabel: "Výber režimu webových partií",
    WebpartModeDescription: "Ako by ste chceli zobraziť webovú časť",
    ShowNavigationLabel: "Zobraziť vlastnú hlavičku navigácie učenia",
    DefaultFilterLabel: "Výber filtra",
    DefaultFilterDescription: "Vyberte filter na obmedzenie výsledkov. Filtrovať môžete len podľa jedného typu naraz.",
    DefaultCategoryLabel: "Filtrovať do kategórie",
    DefaultCategoryDescription: "Vyberte kategóriu, aby ste obmedzili výsledky.",
    DefaultSubCategoryLabel: "Filtrovanie do podkategórie",
    DefaultSubCategoryDescription: "Ak chcete obmedziť výsledky, vyberte podkategóriu.",
    DefaultPlaylistLabel: "Filtrovať do zoznamu skladieb",
    DefaultPlaylistDescription: "Vyberte kategóriu, aby ste obmedzili výsledky.",
    DefaultAssetLabel: "Výber majetku",
    DefaultAssetDescription: "Vyberte aktívum, ktoré sa má zobraziť zo zoznamu skladieb.",
    FilterPanelHeader: "Vyberte si kurzy, ktoré vám najviac vyhovujú",
    FilterPanelAudienceLabel: "Som",
    FilterPanelSkillsetLabel: "Moja zručnosť je",
    NavigationHome: "Domov",
    SearchResultItemPlayListLabel: "Zoznam skladieb: ",
    SearchResultItemCategoryLabel: "Kategória: ",
    SearchPanelPlaceHolderLabel: "Vyhľadávanie zoznamov skladieb alebo aktív",
    LinkPanelCopyLabel: "Kopírovať",
    HeaderPlaylistPanelCurrentPlaylistLabel: "Aktuálny zoznam skladieb: ",
    HeaderPlaylistPanelAdminHeader: "Administratíva",
    PlaylistOverviewDesignMessage: "Počas používania sa v tejto oblasti zobrazia ďalšie aktíva v zozname skladieb, v akom sa zobrazuje.",
    PlaylistOverviewHeading: "Všetky kroky v zozname skladieb",
    BurgerButton: "Burger",
    LinkButton: "Väzba",
    SearchButton: "Hľadať",
    AdministerPlaylist: "Správa zoznamov skladieb",
    NoSearchResults: "Žiadne výsledky vyhľadávania sa nezhodovali s dotazom.",
    DefaultCDNLabel: "Vyberte položku Zdroj učenia",
    DefaultCDNDescription: "Vyberte alternatívny zdroj pre obsah učenia.",
    DescriptionFieldLabel: "Pole popisu",
    ImageSelectorLabel: "Výber obrázka",
    ImageSelectorButton: "Vybrať obrázok",
    DetailEditTitle: "Titul",
    DetailEditDescription: "Popis",
    DetailEditUrl: "Adresa URL",
    DetailEditCategory: "Kategória",
    DetailEditCategoryNoData: "Nie sú k dispozícii žiadne kategórie",
    DetailEditTechnology: "Technológia",
    DetailEditLevel: "Úroveň",
    DetailEditAudience: "Obecenstvo",
    AssetSearchPlaceHolderLabel: "Hľadanie existujúcich aktív",
    CategoryHeading: "Pridanie novej podkategórie",
    CategoryHeadingLabel: "Podkategóriu",
    CategoryPlaylistSavedMessage: "Playlist bol uložený!",
    CategoryPlaylistSaveFailedMessage: "Nepodarilo sa uložiť zoznam skladieb!",
    CategoryNewPlayListMessage: "Vykonali ste zmeny v novom zozname skladieb. Chcete zahodiť zmeny a pokračovať?",
    CategoryEditedPlayListMessage: "V tomto zozname skladieb ste vykonali zmeny. Chcete zahodiť zmeny a pokračovať?",
    PlaylistEditAssetSavedMessage: "Majetok bol zachránený!",
    PlaylistEditAssetSaveFailedMessage: "Nepodarilo sa zachrániť majetok!",
    PlaylistEditCreatePlaylistHeader: "Vytvorenie nového zoznamu skladieb",
    PlaylistEditPlaylistDetailsHeader: "Podrobnosti o zozname skladieb: ",
    PlaylistEditPlaylistAssetsHeader: "Aktíva zoznamu skladieb",
    PlaylistEditEditLabel: "Upraviť podrobnosti",
    PlaylistEditSaveLabel: "Uložiť podrobnosti",
    PlaylistEditCancelLabel: "Zrušiť podrobnosti",
    PlaylistEditCloseLabel: "Zavrieť zoznam skladieb",
    AssetDetailsCreateHeader: "Vytvorenie nového majetku",
    AssetDetailsManageHeader: "Správa vlastného majetku:",
    AssetDetailsDetailsHeader: "Podrobnosti o majetku: ",
    AssetDetailsSaveLabel: "Uložiť majetok",
    AssetDetailsCancelLabel: "Zrušiť majetok",
    AssetDetailsCloseLabel: "Zavrieť aktíva",
    AssetDetailsOpenPage: "Otvoriť stranu",
    TechnologyHeadingLabel: "Technológia",
    SubcategoryHeadingLabel: "Nadpis podkategórie",
    PlaylistItemPlaylistHeadingLabel: "Zoznam skladieb",
    PlaylistItemPlaylistDelete: "Odstrániť zoznam skladieb",
    PlaylistEditAssetNewLabel: "Nové aktívum",
    PlaylistRemove: "Odstrániť zo zoznamu skladieb",
    ImageSelectorImageAlt: "Vlastný zoznam skladieb",
    ImageSelectorUrlPlaceholder: "Adresa url obrázka",
    CategoryHeadingAddPlaylistToSubcategory: "Pridanie nového zoznamu skladieb do podkategórie",
    AdminMenuTechnologyLabel: "Technológia",
    AdminMenuCategoryLabel: "Kategória",
    Show: "Ukázať",
    Hide: "Skryť",
    Add: "Sčítať",
    Edit: "Editovať",
    CloseButton: "Zavrieť",
    EditButton: "Editovať",
    StepButton: "Krok",
    MoveUpButton: "Posunúť sa nahor",
    MoveDownButton: "Posunúť sa nadol",
    SaveButton: "Zachrániť",
    CancelButton: "Zrušiť",
    UpdateButton: "Aktualizovať",
    DeleteButton: "Odstrániť",
    DetailEditNewPageMessage: "Nová stránka s majetkom v knižnici stránok lokalít.",
    DetailEditExistingPageMessage: "Zadajte URL adresu existujúcej stránky.",
    DetailEditNewPageButton: "Vytvoriť stránku s majetkom",
    DetailEditExistingPageButton: "Zadajte adresu URL",
    AdminAddCdnLabel: "Pridanie balíka obsahu",
    AdminEditCdnLabel: "Úprava balíka obsahu",
    AdminDeleteCdnLabel: "Odstrániť balík obsahu",
    AdminCdnIdLabel: "Id/id partnera obsahový balík",
    AdminCdnDisplayName: "Zobrazovaný názov",
    AdminCdnBaseUrl: "Základná adresa URL",
    AdminCustomCdnTitle: "Vlastný balík obsahu",
    AdminCustomCdnDescription: "Vlastné balíky obsahu sú pokročilou funkciou a mali by ich používať iba správcovia so skúsenosťami s administráciou webového obsahu. Nedôveryhodné zdroje obsahu môžu na vašu stránku zaviesť nebezpečný obsah. Mali by ste pridávať iba zdroje, ktorým dôverujete. Ďalšie informácie nájdete v časti Pokyny pre partnerov v dokumentácii o vzdelávacích dráhach.",
    AdminConfirmContentPack: "Spustila sa nová karta prehliadača, ktorá vám umožní poskytnúť nový balík obsahu. Ak tak urobíte úspešne, kliknutím na tlačidlo Dokončiť nižšie aktualizujte zoznam alternatívnych obsahov. Ak máte chybu alebo sa rozhodnete neinštalovať balík obsahu, kliknite na tlačidlo Zrušiť, môžete sa kedykoľvek vrátiť.",
    AdminCdnCompleteButton: "Dokončiť",
    AdminCdnCancelButton: "Zrušiť",
    AdminCdnSaveButton: "Zachrániť",
    AdminCdnUpdateButton: "Aktualizovať",
    AdminRemoveCdn: "Potvrďte, že chcete odstrániť vybraté CDN?",
    AdminAbout: "Webová časť",
    DocumentationLinkLabel: "Otvorená dokumentácia o vzdelávacích dráhach M365",
    CategoryCopyPlaylistFail: "Nepodarilo sa skopírovať zoznam skladieb, obráťte sa na správcu alebo ďalšie podrobnosti nájdete v konzole prehliadača.",
    PlaylistEditCopyLabel: "Kopírovať zoznam skladieb",
    PlaylistNext: "Budúci",
    PlaylistPrevious: "Predchádzajúci",
    PlaylistFullScreen: "Prepnúť režim na celú obrazovku",
    FilterNotSet: "Všetko",
    AdminVersionUpdateNotice: "Nainštalovaná webová časť cesty učenia služby Microsoft 365 je neaktuálna. Momentálne používate verziu %0% a najnovšia verzia je %1%.",
    AdminVersionUpdateInstructions: "Pozrite si pokyny pre 'Aktualizácia riešenia'.",
    AdminSecurityMessage: "Nemáte práva na správu vzdelávacích ciest služby Microsoft 365. Porozprávajte sa so správcom o pripojení sa k skupine Vlastníci alebo Členovia.",
    AdminConfigIssueMessage: "Cesty učenia v službe Microsoft 365 majú problém s konfiguráciou. Požiadajte správcu o pomoc. [Správcovia: Podrobné denníky nájdete v konzole prehliadača. Technickú pomoc si pozrite v zozname problémov na https://github.com/pnp/custom-learning-office-365/issues.]",
    AdminAwaitingUrlPrompt: "VIDEO: Čaká sa na titul...",
    CreatingPage: "Vytvorenie strany",
    TryAgain: "Skús znova",
    AddLanguagePlaceholder: "Pridanie jazyka",
    NotApplicable: "Neuplatňuje sa",
    DataUpgradeTitle: "Inovácia údajov z",
    DataUpgradeIntro: "Aktualizovali ste na významné nové vydanie vzdelávacích ciest služby Microsoft 365. Ak chcete začať proces inovácie, stlačte tlačidlo 'Štart'",
    DataUpgradeStart: "Začiatok",
    DataUpgradeClose: "Zavrieť",
    DataUpgradeIssue: "Ak sa vyskytnú problémy s vykonaním aktualizácie, môžete požiadať o pomoc odoslaním problému ",
    DataUpgradeIssueLink: "Microsoft 365 vzdelávacie cesty zoznam problémov GitHub.",
    DataUpgradeLog: "Denník inovácie",
    DataUpgradeComplete: "Aktualizácia bola dokončená.",
    DataUpgradeErrors: "Chyby",
    LogLevel: "Úroveň",
    LogMessage: "Správa",
    AboutGroupHeader: "M365 vzdelávacie dráhy",
    AboutGroupTitle: "Aktuálna konfigurácia*",
    AboutGroupTitle2: "(* bude aktuálny obsahový balík špecifický)",
    AboutLearningSiteUrl: "Adresa url vzdelávacej lokality:",
    AboutBaseCDNPath: "Základná cesta CDN:",
    AboutTelemetryStatus: "Stav telemetrie:",
    AboutCurrentWPVersion: "Aktuálna verzia webovej časti:",
    AboutMultilingualEnabled: "Povolené viacjazyčné stránky:",
    AboutMultilingualLanguages: "Viacjazyčné jazyky prekladu stránok:",
    AboutConfiguredLanguages: "Konfigurované jazyky:",
    AboutSupportedLanguages: "Obsahový balík podporované jazyky:",
    AboutDefaultSiteLanguage: "Predvolený jazyk lokality:",
    AboutCurrentUserLanguage: "Aktuálny jazyk používateľa:",
    AboutContentPackAssetOrigins: "Pôvod aktív balíka Obsah Pack:",
    AboutCurrentCDN: "Aktuálne CDN:",
    AboutAllCDNs: "Všetky CDN:",
    AboutCacheLastUpdate: "Posledná aktualizácia vyrovnávacej pamäte:",
    DocumentLibraries: "Knižnice dokumentov",
    OpenButtonLabel: "Otvorený",
    CancelButtonLabel: "Zrušiť",
    UploadFileHeader: "Nahrať súbor",
    ChangeFileLinkLabel: "Zmena súboru",
    ChooseFileLinkLabel: "Výber súboru",
    AddFileButtonLabel: "Pridanie súboru",
    WebSearchLinkLabel: "Vyhľadávanie na webe",
    CreativeCommonsMessage: "Tieto výsledky sú označené licenciami Creative Commons. Skontrolujte licencie, aby ste sa uistili, že ich dodržiavate.",
    CopyrightWarning: "Ste zodpovední za rešpektovanie práv iných vrátane autorských práv.",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    LearnMoreLink: "Zistiť viac.",
    NoResultsBadEnglish: "Nenašiel sa žiadny výsledok. Skúste zmeniť možnosti filtrovania",
    SearchResultAlt: "Výsledok obrázka pre {0}.",
    SearchResultAriaLabel: "Stlačením klávesu Enter otvorte zdroj obrázka na novej karte.",
    SearchBoxPlaceholder: "Vyhľadávanie na webe",
    PoweredByBing: "Poháňaný Bingom",
    SizeOptionAll: "Všetko",
    SizeOptionExtraLarge: "Extra veľké",
    SizeOptionLarge: "Veľký",
    SizeOptionMedium: "Stredná",
    SizeOptionSmall: "Malý",
    LayoutOptionAll: "Všetko",
    LayoutOptionSquare: "Námestie",
    LayoutOptionTall: "Vysoký",
    LayoutOptionWide: "Široký",
    LicenseOptionAll: "Všetko",
    LicenseOptionAny: "Iba kreatívne spoločné",
    RecentDocumentsHeader: "Nedávne dokumenty",
    Loading: "Nakladanie...",
    NoRecentFiles: "Žiadne najnovšie súbory",
    NoRecentFilesDescription: "Skúste vybrať súbor z lokality alebo ho nahrať zo zariadenia.",
    EditedByNamePlate: "upravené ",
    LinkHeader: "Z odkazu",
    LinkFileInstructions: "Prilepiť prepojenie na súbor vo OneDrive for Business alebo SharePointe Online",
    NoExternalLinksValidationMessage: "Podporujeme iba prepojenie na súbory vo vašej vlastnej organizácii.",
    ProvidedValueIsInvalid: "Za predpokladaná hodnota je neplatná",
    ImageAriaLabelTemplate: ". obrázok {0}",
    DocumentLabelTemplate: "{0}, Dokument, Upravené {1}, upravené podľa {2}, Súkromné",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}, Priečinok, Upravené {1}, upravené podľa {2}, {3} položiek, Súkromné",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 bajtov",
    SizeUnit: [
      "bytes",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "Výber súborov",
    OrgAssetsTabLabel: "Obrázky a súbory poskytované vašou organizáciou",
    RecentLinkLabel: "Nedávny",
    SiteLinkLabel: "Stavenisko",
    UploadLinkLabel: "Nahrať",
    FromLinkLinkLabel: "Z odkazu",
    TypeAriaLabel: "Operácie stĺpca pre typ súboru, Stlačením zoradíte typ súboru",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "Priečinok",
    ImageAltText: ". obrázok {0}",
    NameField: "Meno",
    SortedAscending: "Zoradené od A do Z",
    SortedDescending: "Zoradené Z na A",
    ModifiedField: "Dátum zmeny",
    ModifiedByField: "Upravené podľa",
    FileSizeField: "Veľkosť súboru",
    OneDriveEmptyFolderAlt: "Prázdny priečinok",
    OneDriveEmptyFolderDescription: "Ak chcete pridať súbory, prejdite do OneDrivu. Súbory do tohto priečinka môžete pridať aj pomocou aplikácie OneDrive pre počítač.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Tento priečinok je prázdny",
    ListLayoutAriaLabel: "Zobraziť možnosti. {0} {1} .",
    ListLayoutCompact: "Kompaktné zobrazenie",
    ListLayoutCompactDescription: "Zobrazenie položiek a podrobností v kompaktnom zozname",
    ListLayoutList: "Zobrazenie zoznamu",
    ListLayoutListDescription: "Zobrazenie položiek a podrobností v zozname",
    ListLayoutTile: "Zobrazenie dlaždíc",
    ListLayoutTileDescription: "Zobrazenie položiek s ukážkami dlaždíc",
    ListOptionsAlt: "Zobraziť možnosti. {0} vybrané .",
    ListOptionsTitle: "Otvorenie ponuky možností zobrazenia",
    Selected: "vybraný",
    CategoryTranslationNotAvailable: "Preklad vybratej podkategórie nie je pre tento jazyk k dispozícii.",
    Abandoned: "Opustený",
    AbandonedPlaylist: "Zoznamy skladieb",
    RemoveLanguageLabel: "Odstrániť jazyk",
    PropertyPaneNone: "žiadny",
    WebPartModeFull: "Plný",
    WebPartModeContentOnly: "Iba obsah",
    PropertyPaneFilterCategory: "Kategória",
    PropertyPaneFilterSubCategory: "Podkategória",
    PropertyPaneFilterPlaylist: "Zoznam skladieb",
    AdminSavingNotification: "Úspora..",
    DataUpgradeReview: "Revízia",
    DataUpgradeMultilingual: "Viacjazyčná podpora je povolená pre vzdelávacie cesty. Skontrolujte jazyky povolené pre lokalitu a vypnite jazyky, ktoré nechcete podporovať.",
    M365Title: "Cesty vzdelávania v službe Microsoft 365",
    ValidateBase: "Základná adresa URL pre CDN musí skončiť na (/).",
    CustomizeSort: "Prispôsobenie zoradenia",
    ResetSort: "Obnoviť zoradenie"
  };
});
