name: BuildWebParts

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'     
        required: true
        default: 'translate'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildWebPart:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          ref: ${{ github.event.inputs.branch }}
      - name: Go to webparts dir
        run: cd src/webpart
      - name: Install tools
        run: npm ci
      - name: Compile Web Parts
        run: gulp bundle --ship
      - name: Package Web Parts
        run: gulp package-solution --ship
