name: Build (no) WebParts and Manifest

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      sourceBranch:
        description: 'Branch'     
        required: true
        default: 'translate'

jobs:
  PackManifest:
    uses: petrmo/custom-learning-office-365/.github/workflows/ZipTeamsPlugin.yml@main
    with:
      branch: ${{ github.event.inputs.sourceBranch }}
