name: BuildWebParts

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'     
        required: true
        default: 'translate'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildWebPart:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          ref: ${{ github.event.inputs.branch }}
      - name: Install tools
        run: |
          cd src/webpart
          npm ci
      - name: Compile Web Parts
        run: |
          cd src/webpart
          gulp bundle --ship
      - name: Package Web Parts
        run: |
          cd src/webpart
          gulp package-solution --ship
      - uses: actions/upload-artifact@v2
        with:
          name: Webparts
          path: sharepoint\solution\customlearning.sppkg
