# This is a basic workflow to help you get started with Actions

name: Translations

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  translate:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          ref: translate
      # Runs a set of commands using the runners shell
      - name: Translate
        env: 
          ocp_opim_key:${{secrets.OCPAPIMSUBSCRIPTIONKEY}}
        run: |
          $header = @{"Ocp-Apim-Subscription-Key"=$env:ocp_opim_key; "Content-type"="Application/json; charset=UTF-8"}
          $lines = Get-Content -LiteralPath "src\webpart\src\webparts\common\loc\en-us.ts" -Encoding UTF8
          
          for($i = 0; $i -lt $lines.Length; $i++ )
          {
            $line = $lines[$i]
            if ($line -match "(.+): `"(.+)`"")
            {
                  $text = $matches[1]
                  $translate = Invoke-RestMethod "https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&from=en&to=cs" -Method Post -body "[{'Text':'$text'}]" -Headers $header
                  $line = $line.Replace($text, $translate[0].translations[0].text) + " //originalEnglish:$text"
              }

              $line >> "src\webpart\src\webparts\common\loc\cs-cz.ts"
          }
      - name: Commit
        run: |
          git add --all
          git commit -m "Translations"
          
          

          
