# This is a basic workflow to help you get started with Actions

name: Zip Teams plugin

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      branch:
        description: 'Branch'     
        required: true
        default: 'translate'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  zip:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          ref: ${{ github.event.inputs.branch }}

      - name: Zip teams plugin
        run: 7z.exe a teams.zip ./CustomTranslations/manifest.json ./src/webpart/teams/141d4ab7-b6ca-4bf4-ac59-25b7bf93642d_color.png ./src/webpart/teams/141d4ab7-b6ca-4bf4-ac59-25b7bf93642d_outline.png 

      - uses: actions/upload-artifact@v2
        name: Upload artifacts
        with:
          name: TeamsPlugin
          path: teams.zip

